[package]
name = "Fraktivitaeten"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

uuid = { version = "1.23.4", features = ["v4", "serde"] }
chrono = { version = "0.4.44", features = ["serde"] }
rand = {version = "0.10"}
rand_distr = {version = "0.6"}
good_lp = { version = "*" }

[profile.release]
debug = true